### ISSUE TITLE
laravel 连接mariadb

### ISSUE THREAD

**Issue by wifidu** [yansongda/docker-compose-LNMP#1]
请问你用host=localhost连接数据库时，出过问题吗？
我出现了以下问题，
> SQLSTATE[HY000] [2002] No such file or directory
网上说：
> 要改`php.ini`里面的pdo_mysql.default_socket=/var/lib/mysql/mysql.sock

**但是**php容器里没有这个文件呀。
当我改用127.0.0.1连接时，直接拒绝，因为mariadb根本没有创建这个host的账户
可能我的是特例，但是能给我讲讲怎么才能成功连接呢，或者怎么改配置
特别感谢！

**Comment by yansongda** [comment]
使用容器时，host 直接指定为 service 名称即可

**Comment by wifidu** [comment]
谢谢你！我刚开始学用docker，谢谢你的帮助:heart:
